# Generated by Django 2.2.3 on 2019-07-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190731_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
    ]
