# Generated by Django 2.2.3 on 2019-07-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190731_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('C', 'Camisetas'), ('J', 'Jaquetas'), ('T', 'Tênis')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
