# Generated by Django 2.2.3 on 2019-07-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_items_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
