# Generated by Django 2.2.3 on 2019-08-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_items_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='Description default'),
            preserve_default=False,
        ),
    ]
